---

version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile.app
      context: .
    environment:
      PORT: 3000
      SECRET_KEY_BASE: test
      RAILS_ENV: development
    ports:
      - 3000:3000
